version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql
    hostname: mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "DockerSql2017!"
    restart: unless-stopped
    ports:
      - 1433:1433
    networks: 
      - red
  employers-api:
    image: employers-api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - DB_CONNECTION_STRING=Server=localhost,1433;Database=BD03;User ID=SA;Password=DockerSql2017!
    build:
      context: .
      dockerfile: src/employers.api/Dockerfile
    ports:
      - 5000:80
    depends_on: 
      - db
    networks: 
      - red
networks: 
  red:
    driver: bridge
