version: 2.1

workflows:
  version: 2
  test:
    jobs:
      - build-net6
      - test-netcore:
          name: .NET 6.0
          docker-image: mcr.microsoft.com/dotnet/sdk:6.0
          build-target-framework: netstandard2.0
          test-target-framework: net6.0
          requires:
            - build-net6

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default

    steps:
      - checkout
      - run:
          name: "Restore projects"
          command: dotnet restore employer.solution.sln
      - run:
          name: "Build projects"
          command: dotnet build employer.solution.sln
      - run:
          name: "Running Api Tests"
          command: dotnet test test/employer.api.tests\ -v n --results-directory:test_coverage --collect:"Code Coverage"
      - run:
          name: "Running Application Tests"
          command: dotnet test test/employer.application.tests\ -v n --results-directory:test_coverage --collect:"Code Coverage"
      - store_artifacts:
          path: C:\Users\circleci\project\test_coverage
      - store_test_results:
          path: C:\Users\circleci\project\test_result
