version: 2.1

orbs:
    win: circleci/windows@5

jobs:
    build:
        executor: win/default

        steps:
            - checkout
            - run:
                  name: "Restore projects"
                  command: dotnet restore employer.solution.sln
            - run:
                  name: "Build projects"
                  command: dotnet build employer.solution.sln
            - run:
                  name: "Running Api Tests"
                  command: dotnet test test/employer.api.tests
            - run:
                  name: "Running Application Tests"
                  command: dotnet test test/employer.application.tests\ --logger:"junit;LogFilePath=test-results/xunit.xml"
            - store_artifacts:
                  path: ./test/employer.application.tests/test-results
            - store_test_results:
                  path: ./test/employer.application.tests/test-results
