version: 2.1

orbs:
    win: circleci/windows@5

jobs:
    build:
        executor: win/default

        steps:
            - checkout
            - run:
                  name: "Restore projects"
                  command: dotnet restore employer.solution.sln
            - run:
                  name: "Build projects"
                  command: dotnet build employer.solution.sln
            - run:
                  name: "Running Api Tests"
                  command: dotnet test test/employer.api.tests\ -v n --results-directory:test_coverage --collect:"Code Coverage"
            - run:
                  name: "Running Application Tests"
                  command: dotnet test test/employer.application.tests\ -v n --results-directory:test_coverage --collect:"Code Coverage"
            - store_artifacts:
                  path: C:\Users\circleci\project\test_coverage
            - store_test_results:
                  path: C:\Users\circleci\project\test_result
