CREATE TABLE Department
(
    ID_DEPARTMENT INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
    MANAGER INT NOT NULL,
    NOM_DEPARTMENT VARCHAR(50) NOT NULL,
    DESC_DEPARTMENT VARCHAR(250) NOT NULL
);

GO

CREATE TABLE Occupation
(
    ID_OCCUPATION INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
    NOM_OCCUPATION VARCHAR(50) NOT NULL,
    LEVEL_OCCUPATION VARCHAR(50) NOT NULL
);

GO

CREATE TABLE Employee
(
    ID_EMPLOYEE INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
    NOM_EMPLOYEE VARCHAR(50),
    GENDER CHAR(1),
    ACTIVE BIT NOT NULL,
    ID_DEPARTMENT INT REFERENCES Department(ID_DEPARTMENT),
    ID_OCCUPATION INT REFERENCES Occupation(ID_OCCUPATION)
);
